name: Build and Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install UV
      uses: astral-sh/setup-uv@v4

    - name: Update version in pyproject.toml
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        # Update version in pyproject.toml
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml

    - name: Build and Publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv build
        uv publish
